apiVersion: v2
name: 0xnetworth
description: A Helm chart for 0xNetworth - Investment Tracking Dashboard
type: application
version: 0.3.13
appVersion: "0.3.13"
keywords:
  - investment
  - dashboard
  - coinbase
  - networth
maintainers:
  - name: 0xNetworth Team
home: https://github.com/0xJMart/0xNetworth
sources:
  - https://github.com/0xJMart/0xNetworth

